[dev]
  targetPort = 3000

[[redirects]]
  from = "/cms/*"
  to = "cms/admin/:splat"
  force = true
  status = 200
  conditions = {Role = ["admin"]}
[[redirects]]
  from = "/cms/*"
  to = "/cms/motw/:splat"
  force = true
  status = 200
  conditions = {Role = ["motw"]}
