local_backend: true
backend:
  name: git-gateway
  branch: master
collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: src/collections/posts
    create: true
    fields:
      - name: title
        label: Title
      - name: section
        label: Section
        hint: This will decide which section the post appears in on the homepage and article collection pages.
        widget: select
        options:
          - { label: 'Announcements', value: 'announcements' }
          - { label: 'Articles', value: 'articles' }
          - { label: 'Speciality', value: 'speciality' }
      - name: category
        label: Category
        hint: This will determine what label will show above the post title.
        widget: select
        options:
          - { label: 'None', value: '' }
          - { label: 'Announcement', value: 'announcement' }
          - { label: 'News', value: 'news' }
          - { label: 'Guide', value: 'guide' }
          - { label: 'Interview', value: 'interview' }
          - { label: 'Event', value: 'event' }
      - name: publish
        label: Publish Date
        widget: datetime
      - name: homepageText
        label: Homepage Text
        required: false
        hint: This text is used when displaying this post as a component of the homepage. If not provided, the title will be used.
      - name: body
        label: Body
        widget: markdown
      - name: image
        label: Image
        widget: image
        required: false
        media_folder: /static/uploads/posts
        choose_url: false
      - name: showInPostListing
        label: Show in post listing
        widget: boolean
        default: true
  - name: map-of-the-week
    label: Map of the Week
    folder: src/collections/map-of-the-week
    slug: '{{startDate}}'
    create: true
    fields:
      - name: mapId
        label: Map  ID
        hint: The BeatSaver ID of the map of the week. You can find this one in the URL of the map's page on beatsaver.com. For example, the ID of the map https://beatsaver.com/maps/8f is the last part 8f.
      - name: review
        label: Review
        hint: 'An accompanying text to the map of the week that should review and ideally describe what made it the MOTW. Example "This map has a fantastic lightshow on the new Lattice environment, a poodle diff and three other diffs accessible to a variety of players with great and unique usage of arcs."'
        widget: text
      - name: startDate
        label: Start Date
        hint: Starting when the map of the week should be displayed on the root page.
        default: 2024-01-01T00:00:00Z
        widget: datetime
      - name: coverUrlOverwrite
        label: Cover URL
        required: false
        hint: If you want to use a different cover image than the one fetched from BeatLeader, you can provide a URL here.
        widget: string
  - name: community-labels
    label: Community Labels
    folder: src/collections/community-labels
    slug: '{{label}}'
    create: true
    fields:
      - name: label
        label: Label
        widget: string
      - name: description
        label: Description
        widget: string
      - name: color
        label: Color
        widget: color
  - name: community
    label: Community
    folder: src/collections/communities
    create: true
    fields:
      - name: name
        label: Name
      - name: description
        label: Description
        widget: text
      - name: image
        label: Image
        widget: image
        required: false
        media_folder: /static/uploads/communities
        choose_url: false
      - name: labels
        label: Labels
        widget: relation
        collection: community-labels
        multiple: true
        search_fields: [label]
        value_field: label
        display_fields: [label]
      - name: socials
        label: Socials
        widget: list
        multiple: true
        fields:
          - {
              label: Name,
              name: name,
              widget: select,
              options:
                [
                  'Discord',
                  'Twitter/X',
                  'Facebook',
                  'Instagram',
                  'Twitch',
                  'YouTube',
                  'Reddit',
                  'GitHub',
                  'Website',
                ],
            }
          - { label: URL, name: url, widget: string }
          - {
              label: Title Overwrite,
              name: titleOverwrite,
              widget: string,
              hint: The title is the text that appears if you hover over the icon. If you want to overwrite it,
              you can do so here. Otherwise,
              the title will be the same as the name that has been selected.,
              required: false,
            }
media_folder: 'static/uploads'
public_folder: '/uploads'
