local_backend: true
backend:
  name: git-gateway
  branch: master
collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: src/collections/posts
    create: true
    fields:
      - name: title
        label: Title
      - name: section
        label: Section
        hint: This will decide which section the post appears in on the homepage and article collection pages.
        widget: select
        options:
          - { label: 'Announcement', value: 'announcements' }
          - { label: 'News', value: 'news' }
          - { label: 'Music Pack', value: 'music-packs' }
          - { label: 'Community Event', value: 'community-events' }
          - { label: 'Map of the Week', value: 'maps-of-the-week' }
      - name: publish
        label: Publish Date
        widget: datetime
      - name: homepageText
        label: Homepage Text
        required: false
        hint: This text is used when displaying this post as a component of the homepage. If not provided, the title will be used.
      - name: body
        label: Body
        widget: markdown
      - name: image
        label: Image
        widget: image
        required: false
        media_folder: /static/uploads/posts
        choose_url: false
  - name: curation-team
    label: Curation Team
    slug: '{{name}}'
    folder: src/collections/curation-team
    create: true
    fields:
      - name: name
      - name: slug
      - name: role
        widget: select
        options: [Curator, Senior Curator]
      - name: style_tags
        widget: list
        allow_add: true
      - name: favorite_map
        widget: object
        fields:
          - name: name
          - name: url
      - name: bio
        widget: markdown
      - name: image
        widget: image
        media_folder: /static/uploads/curators
        choose_url: false
  - name: map-of-the-week
    label: Map of the Week
    folder: src/collections/map-of-the-week
    slug: '{{year}}-{{week}}'
    create: true
    fields:
      - name: mapId
        label: Map  ID
        hint: The BeatSaver ID of the map of the week. You can find this one in the URL of the map's page on beatsaver.com. For example, the ID of the map https://beatsaver.com/maps/8f is the last part 8f.
      - name: nominatorId
        label: Nominator ID
        hint: The BeatSaver ID of the nominator. You can find this one in the URL of the user's profile on beatsaver.com. For example, symphonics profil link is https://beatsaver.com/profile/4292041, his ID would be the last part, so 4292041.
      - name: remark
        label: Remark
        hint: "An accompanying text to the map of the week that should describe what made it the MOTW. Example \"This map has a fantastic lightshow on the new Lattice environment, a poodle diff and three other diffs accessible to a variety of players with great and unique usage of arcs.\""
        widget: markdown
      - name: remarkAuthorId
        label: Remark Author ID
        hint: The BeatSaver ID of the author of the remark. You can find this one in the URL of the user's profile on beatsaver.com. For example, symphonics profil link is https://beatsaver.com/profile/4292041, his ID would be the last part, so 4292041.
      - name: year
        label: Year
        hint: The year when this map is map of the week.
        default: 2024
        widget: number
        min: 2019 # Release Year of Beat Saber
        step: 1
      - name: week
        label: Week
        hint: "The week when this map is map of the week. For example, the first week of the year 2024 started on December 31, 2023, since Sunday is the marking point of the week. The map will still be shown on the next Monday. Confused what would be the right week number? See here: https://www.calendar-365.com/week-number.html"
        widget: number
        min: 1
        max: 53
        step: 1
media_folder: 'static/uploads'
public_folder: '/uploads'
